version: "1"

services:
  count:
    build: ./
    command: python app.py
    ports:
      - "80:80"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
      - POSTGRES_DATABASE_NAME=